name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular
        run: ng build --configuration=production

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy a Firebase Hosting
        run: firebase deploy --only hosting --project luis-tapia --token "${{ secrets.FIREBASE_TOKEN }}"